import { GlobalStateProvider } from '@/context/GlobalStateProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gifte',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <body className={inter.className}>
          {children}
        </body>
      </GlobalStateProvider>
    </html>
  )
}
