import { GlobalStateProvider } from '@/context/GlobalStateProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <body className={inter.className}>
          <div id='body' className=" w-full max-w-[425px] h-screen overflow-hidden mx-auto ">
            {children}
          </div>
        </body>
      </GlobalStateProvider>
    </html>
  )
}
